version: '3.8'
services: 
    api-service:
        build: ./api-SQUAD/
        volumes: 
            - ./api-SQUAD/:/usr/src/app/
        ports: 
            - 5004:5004
        environment: 
            PORT: 5004
            FLASK_DEBUG: 1
