version: '3.8'
services:  
    dbnosql:
        image: mongo:latest
        environment:
            MONGO_INITDB_DATABASE: apisquad
            MONGO_INITDB_ROOT_PASSWORD: vagrant3
            MONGO_INITDB_ROOT_USERNAME: admin
        command: mongod --port 28108
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./mongo_backup:/data/backup
            - mongodataSquad:/data/db
        ports:
            - 28108:28108
    api-service:
        build: ./apiSQUAD/
        volumes: 
            - ./apiSQUAD/:/usr/src/app/
        ports: 
            - 5004:5004
        environment: 
            PORT: 5004
            FLASK_DEBUG: 1

volumes:
  mongodataSquad:
    driver: local